version: '3.8' 

services: 
  backend: 
    build: ./back      
    ports:
    - "5000:5000"         
  
  frontend: 
    build: ./public     
    ports:
    - "3000:80"           
    depends_on:
    - backend             